### ISSUE TITLE
Process correlator uuid and apply sha 512 transformation

### ISSUE THREAD

**Issue by rtyler** [jenkins-infra/uplink#15]
New events should have a modified correlator id which takes the legacy UUID and concatenates with the event type to create an event-specific correlator./

See also: https://issues.jenkins-ci.org/browse/JENKINS-54136

**Comment by rtyler** [comment]
This is blocked until the corresponding core change is merged.

**Comment by daniel-beck** [comment]
Corresponding core PR at https://github.com/jenkinsci/jenkins/pull/3698 -- these need to provide the same output.

**Comment by rtyler** [comment]
@daniel-beck would you mind including in this ticket an example of a type, original correlator, and the resulting sha256? Just so I can add a unit test for that

**Comment by daniel-beck** [comment]
@rtyler https://github.com/jenkinsci/jenkins/pull/3698/commits/37f725f5706dddccf235109ff1101405b0fc5bb4#diff-6fc932078349e57bceeeea758fae09dbR77 should do it?
